// export const UPDATE_CAMERA_STATE = 'UPDATE_CAMERA_STATE'
export const SHOW_LISTING = 'SHOW_LISTING'
export const CODE_PRICE_CHANGE = 'CODE_PRICE_CHANGE'
export const SUBMIT_VALUE = 'SUBMIT_VALUE'
export const DELETE_VALUE = 'DELETE_VALUE'
export const DATA_IS_PUSHED = 'DATA_IS_PUSHED'
export const ITEM_COUNTER = 'ITEM_COUNTER'
export const TOKEN_CHECKED = 'TOKEN_CHECKED'
export const USER = 'USER'








