// export const UPDATE_CAMERA_STATE = 'UPDATE_CAMERA_STATE'
export const SHOW_LISTING = 'SHOW_LISTING'
export const SUBMIT_VALUE = 'SUBMIT_VALUE'
export const DELETE_VALUE = 'DELETE_VALUE'
export const REPORT = 'REPORT'
export const DATA_IS_PUSHED = 'DATA_IS_PUSHED'
export const ITEM_COUNTER = 'ITEM_COUNTER'





